use ds;
#匕首类
insert into items value("Dagger", "weapons", "dagger", "匕首", "dagger-icon.png");
insert into items value("Parrying Dagger", "weapons", "dagger", "招架匕首", "parrying_dagger-icon.png");
insert into items value("Mail Breaker", "weapons", "dagger", "破甲细剑", "mail_breaker-icon.png");
insert into items value("Bandit's Knife", "weapons", "dagger", "盗贼短刀", "bandits_knife-icon.png");
insert into items value("Rotten Ghru Dagger", "weapons", "dagger", "咕噜腐败刀", "rotten_ghru_dagger-icon.png");
insert into items value("Corvian Greatknife", "weapons", "dagger", "鸦人大短刀", "corvian_greatknife-icon.png");
insert into items value("Handmaid's Dagger", "weapons", "dagger", "侍女匕首", "handmaids_dagger-icon.png");
insert into items value("Scholar's Candlestick", "weapons", "dagger", "贤者烛台", "scholars_candlestick-icon.png");
insert into items value("Tailbone Short Sword", "weapons", "dagger", "尾骨短剑", "tailbone_short_sword-icon.png");
insert into items value("Brigand Twindaggers", "weapons", "dagger", "盗贼双刀", "brigand_twindaggers-icon.png");
insert into items value("Harpe", "weapons", "dagger", "镰刀剑", "harpe-icon.png");
insert into items value("Aquamarine Dagger", "weapons", "dagger", "蓝宝石匕首", "aquamarine_dagger-icon.png");
insert into items value("Murky Hand Scythe", "weapons", "dagger", "濡湿小镰刀", "murky_hand_scythe.png");
#直剑类
insert into items value("Shortsword", "weapons", "straight sword", "短剑", "shortsword-icon.png");
insert into items value("Long Sword", "weapons", "straight sword", "长剑", "longsword-icon.png");
insert into items value("Broadsword", "weapons", "straight sword", "阔剑", "broadsword-icon.png");
insert into items value("Broken Straight Sword", "weapons", "straight sword", "已折断的直剑", "broken_straight_sword-icon.png");
insert into items value("Astora Straight Sword", "weapons", "straight sword", "亚斯特拉直剑", "astora_straight_sword-icon.png");
insert into items value("Lothric Knight Sword", "weapons", "straight sword", "洛斯里克骑士剑", "lothric_knight_sword-icon.png");
insert into items value("Barbed Straight Sword", "weapons", "straight sword", "针刺直剑", "barbed_straight_sword-icon.png");
insert into items value("Dark Sword", "weapons", "straight sword", "黑暗剑", "dark_sword-icon.png");
insert into items value("Cleric's Candlestick", "weapons", "straight sword", "圣者烛台", "clerics_candlestick-icon.png");
insert into items value("Irithyll Straight Sword", "weapons", "straight sword", "伊鲁席尔直剑", "irithyll_straight_sword-icon.png");
insert into items value("Anri's Straight Sword", "weapons", "straight sword", "安里的直剑", "anris_straight_sword-icon.png");
insert into items value("Sunlight Straight Sword", "weapons", "straight sword", "太阳直剑", "sunlight_straight_sword-icon.png");
insert into items value("Morion Blade", "weapons", "straight sword", "摩利安刃剑", "morion_blade-icon.png");
insert into items value("Lothric's Holy Sword", "weapons", "straight sword", "洛斯里克圣剑", "lothrics_holy_sword-icon.png");
insert into items value("Gotthard Twinswords", "weapons", "straight sword", "歌徳希尔对剑", "gotthard_twinswords-icon.png");
insert into items value("Valorheart", "weapons", "straight sword", "果敢的心", "valorheart-icon.png");
insert into items value("Ringed Knight Straight Sword", "weapons", "straight sword", "环印骑士直剑", "ringed_knight_straight_sword.png");
#小盾
insert into items value("Buckler", "shields", "small", "小圆盾", "buckler-icon.png");
insert into items value("Red and White Shield", "shields", "small", "红白圆盾", "red_and_white_shield-icon.png");
insert into items value("Elkhorn Round Shield", "shields", "small", "鹿角圆盾", "small_shield-icon.png");
insert into items value("Target Shield", "shields", "small", "团牌", "target_shield-icon.png");
insert into items value("Iron Round Shield", "shields", "small", "铁圆盾", "iron_round_shield-icon.png");
insert into items value("Warrior's Round Shield", "shields", "small", "战士圆盾", "warriors_round_shield-icon.png");
insert into items value("Hawkwood's Shield", "shields", "small", "霍克伍德盾", "hawkwoods_shield-icon.png");
insert into items value("Caduceus Round Shield", "shields", "small", "孪生蛇纹圆盾", "caduceus_round_shield-icon.png");
insert into items value("Crimson Parma", "shields", "small", "红圆盾", "crimson_parma-icon.png");
insert into items value("Leather Shield", "shields", "small", "皮盾", "leather_shield-icon.png");
insert into items value("Sacred Bloom Shield", "shields", "small", "圣花盾", "sacred_bloom_shield-icon.png");
insert into items value("Small Leather Shield", "shields", "small", "小皮盾", "small_leather_shield-icon.png");
insert into items value("Llewellyn Shield", "shields", "small", "林德盾", "llewellyn_shield-icon.png");
insert into items value("Golden Falcon Shield", "shields", "small", "金鹰小盾", "golden_falcon_shield-icon.png");
insert into items value("Eastern Iron Shield", "shields", "small", "东方铁盾", "eastern_iron_shield-icon.png");
insert into items value("Plank Shield", "shields", "small", "木板盾", "plank_shield-icon.png");
insert into items value("Ghru Rotshield", "shields", "small", "咕噜腐败盾", "ghru_rotshield-icon.png");
select * from items;